### ISSUE TITLE
Layout Structure

### ISSUE THREAD

**Issue by hrittikhere** [hrittikhere/getting-started-with-aks#1]
Hey @vishipayyallore 
What will be the best layout for this repository? I have two options feel free to suggest if there's something better:
Option 1:
Primary `README.MD` discussing Day 1, Day 2, Day 3...... as we with a brief overview of each day and then linking to Detailed Docs inside a `/documentation` directory at home directory. `/manifests` in the manifest directory 

Option 2:

Primary `README.MD` discussing Day 1, Day 2, Day 3 and directories like `Day1`, `Day2` Inside the home directory with all the manifests and docs in it. 

## Getting started with AKS using Terraform, GitHub Actions
Step 1: Intro to k8s - 10 mins
Step 2: Deploy an AKS using Portal (Manually) - 15 mins
Step 3: Introduction to Terraform - 10 mins
Step 4: Deploy an AKS using Terraform - 15 mins
Step 5: Introduction to GitHub Actions - 10 mins
Step 6: Deploy AKS using GitHub Actions - 20 mins

**Comment by vishipayyallore** [comment]
@hrittikhere 
Good evening. We will discuss this in our mentoring session on 09-May. Many thanks.

**Regards
Swamy**

**Comment by hrittikhere** [comment]
Please add a pull request when you add the Terraform Modules @vishipayyallore :) It'll help me to stay updated and move forward.

**Comment by vishipayyallore** [comment]
> Please add a pull request when you add the Terraform Modules @vishipayyallore :) It'll help me to stay updated and move forward.

On it @hrittikhere
